# Generated by Django 5.2.17 on 2026-08-19 18:06

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import procurement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default=procurement.models._uuid_str, max_length=50, unique=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('approver_tier', models.CharField(choices=[('manager', 'Manager'), ('finance', 'Finance'), ('cfo', 'Cfo'), ('sole_source_committee', 'Sole Source Committee')], max_length=30)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('ai_risk_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default=procurement.models._uuid_str, max_length=50, unique=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('context_json', models.JSONField(default=dict)),
                ('policy_citations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_number', models.CharField(default=procurement.models._uuid_str, max_length=50, unique=True)),
                ('received_by', models.CharField(max_length=100)),
                ('quality_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partial', 'Partial')], max_length=20)),
                ('quality_notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_number', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('material_group', models.CharField(max_length=100)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lead_time_days', models.IntegerField(default=7)),
                ('reorder_point', models.IntegerField(default=0)),
                ('stock_qty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['material_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(default=procurement.models._uuid_str, max_length=50, unique=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent_to_vendor', 'Sent To Vendor'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('invoiced', 'Invoiced'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('is_sole_source', models.BooleanField(default=False)),
                ('sole_source_justification', models.TextField(blank=True)),
                ('policy_compliance_notes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.CharField(default=procurement.models._uuid_str, max_length=50, unique=True)),
                ('requester', models.CharField(max_length=100)),
                ('cost_center', models.CharField(max_length=50)),
                ('justification', models.TextField()),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted_to_po', 'Converted To Po')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(default='NET30', max_length=50)),
                ('material_groups', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('under_review', 'Under Review'), ('blacklisted', 'Blacklisted')], default='approved', max_length=20)),
                ('on_time_delivery_pct', models.FloatField(default=0.0)),
                ('quality_rating', models.FloatField(default=0.0)),
                ('price_competitiveness', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('total_orders', models.IntegerField(default=0)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['vendor_code'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('policy_type', models.CharField(choices=[('spending_limit', 'Spending Limit'), ('approved_vendor', 'Approved Vendor'), ('category_rule', 'Category Rule'), ('sole_source', 'Sole Source'), ('compliance', 'Compliance'), ('general', 'General')], max_length=30)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['policy_type', 'title'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='policy_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_date', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.material')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='GRLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.goodsreceipt')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.polineitem')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('vendor_invoice_ref', models.CharField(max_length=100)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('match_status', models.CharField(choices=[('pending_match', 'Pending Match'), ('matched', 'Matched'), ('discrepancy', 'Discrepancy'), ('approved_for_payment', 'Approved For Payment'), ('paid', 'Paid')], default='pending_match', max_length=30)),
                ('match_discrepancies', models.JSONField(blank=True, default=list)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_pr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.purchaserequisition'),
        ),
        migrations.CreateModel(
            name='PRLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_date_needed', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.material')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.purchaserequisition')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.vendormaster'),
        ),
    ]
