# Generated by Django 5.2.17 on 2026-08-19 18:22

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent_to_vendor', 'Sent To Vendor'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('invoiced', 'Invoiced'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
